set_property PACKAGE_PIN P18 [get_ports MUTE]
set_property IOSTANDARD LVCMOS33 [get_ports MUTE]
set_property IOSTANDARD LVCMOS33 [get_ports MCLK]
set_property IOSTANDARD LVCMOS33 [get_ports PBLRC]
set_property IOSTANDARD LVCMOS33 [get_ports BCLK]
set_property IOSTANDARD LVCMOS33 [get_ports PBDAT]
set_property PACKAGE_PIN T19 [get_ports MCLK]
set_property PACKAGE_PIN M18 [get_ports PBLRC]
set_property PACKAGE_PIN K18 [get_ports BCLK]
set_property PACKAGE_PIN M17 [get_ports PBDAT]

set_property IOSTANDARD LVCMOS33 [get_ports iic_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_sda_io]
set_property PACKAGE_PIN N18 [get_ports iic_0_scl_io]
set_property PACKAGE_PIN N17 [get_ports iic_0_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports BCLK_1]
set_property IOSTANDARD LVCMOS33 [get_ports PBDAT_1]
set_property IOSTANDARD LVCMOS33 [get_ports MCLK_1]
set_property IOSTANDARD LVCMOS33 [get_ports PBLRC_1]
set_property IOSTANDARD LVCMOS33 [get_ports MUTE_1]
set_property PACKAGE_PIN V12 [get_ports BCLK_1]
set_property PACKAGE_PIN W16 [get_ports PBDAT_1]
set_property PACKAGE_PIN J15 [get_ports MCLK_1]
set_property PACKAGE_PIN H15 [get_ports PBLRC_1]
set_property PACKAGE_PIN V13 [get_ports MUTE_1]

