# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.cache/wt [current_project]
set_property parent.project_path /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /home/jaxc/FPGA/IP [current_project]
set_property ip_output_repo /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/ip/top_Jaxc_I2S_0_0/sources_1/ip/Output_buffer_Block_RAM/BLK_init.coe
read_vhdl -library xil_defaultlib /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/hdl/top_wrapper.vhd
add_files /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/top.bd
set_property used_in_implementation false [get_files -all /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/ip/top_Jaxc_I2S_0_0/sources_1/ip/Output_buffer_Block_RAM/Output_buffer_Block_RAM_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/ip/top_Jaxc_I2S_0_0/clk_wiz_0/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/ip/top_Jaxc_I2S_0_0/clk_wiz_0/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/ip/top_Jaxc_I2S_0_0/constrs_1/imports/constraints/i2s.xdc]
set_property used_in_implementation false [get_files -all /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/ip/top_rst_ps7_0_100M_0/top_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/ip/top_rst_ps7_0_100M_0/top_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/ip/top_rst_ps7_0_100M_0/top_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/ip/top_auto_pc_0/top_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/top_ooc.xdc]
set_property is_locked true [get_files /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/sources_1/bd/top/top.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/constrs_1/new/DJ.xdc
set_property used_in_implementation false [get_files /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.srcs/constrs_1/new/DJ.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef top_wrapper.dcp

catch { report_utilization -file top_wrapper_utilization_synth.rpt -pb top_wrapper_utilization_synth.pb }
