webtalk_init -webtalk_dir /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec 21 14:12:37 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2016.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1682563" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6e244557-6cf1-413d-ac99-6301f3595063" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 17.2 Rafaela" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 17.2 Rafaela" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 17.2 Rafaela" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 17.2 Rafaela" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 17.2 Rafaela" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 17.2 Rafaela" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1199.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_transmit -clientid 2060187569 -regid "" -xml /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.hw/webtalk/usage_statistics_ext_labtool.xml -html /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.hw/webtalk/usage_statistics_ext_labtool.html -wdm /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
