# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.tmp/axi_i2s_adi_v1_0_project/axi_i2s_adi_v1_0_project.cache/wt [current_project]
set_property parent.project_path /home/jaxc/FPGA/DJ-Jaxc/DJ/DJ.tmp/axi_i2s_adi_v1_0_project/axi_i2s_adi_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/jaxc/FPGA/IP
  /home/jaxc/FPGA/zybo_base_system/source/vivado/hw/ip_repo
} [current_project]
read_vhdl -library axi_i2s_adi_v1_00_a {
  /home/jaxc/FPGA/IP/ADI/axi_i2s_adi_1.0/hdl/i2s_tx.vhd
  /home/jaxc/FPGA/IP/ADI/axi_i2s_adi_1.0/hdl/fifo_synchronizer.vhd
  /home/jaxc/FPGA/IP/ADI/axi_i2s_adi_1.0/hdl/i2s_rx.vhd
  /home/jaxc/FPGA/IP/ADI/axi_i2s_adi_1.0/hdl/i2s_clkgen.vhd
  /home/jaxc/FPGA/IP/ADI/axi_i2s_adi_1.0/hdl/i2s_controller.vhd
}
read_vhdl -library adi_common_v1_00_a {
  /home/jaxc/FPGA/IP/ADI/axi_i2s_adi_1.0/hdl/adi_common/dma_fifo.vhd
  /home/jaxc/FPGA/IP/ADI/axi_i2s_adi_1.0/hdl/adi_common/axi_streaming_dma_rx_fifo.vhd
  /home/jaxc/FPGA/IP/ADI/axi_i2s_adi_1.0/hdl/adi_common/axi_ctrlif.vhd
  /home/jaxc/FPGA/IP/ADI/axi_i2s_adi_1.0/hdl/adi_common/pl330_dma_fifo.vhd
  /home/jaxc/FPGA/IP/ADI/axi_i2s_adi_1.0/hdl/adi_common/axi_streaming_dma_tx_fifo.vhd
}
read_vhdl -library work /home/jaxc/FPGA/IP/ADI/axi_i2s_adi_1.0/hdl/axi_i2s_adi.vhd
synth_design -top axi_i2s_adi -part xc7z010clg400-1
write_checkpoint -noxdef axi_i2s_adi.dcp
catch { report_utilization -file axi_i2s_adi_utilization_synth.rpt -pb axi_i2s_adi_utilization_synth.pb }
